# Generated by Django 4.0.4 on 2022-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=105)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
